#path where raw fastq reads are stored
readfolder: "../workflow/test_data/"
#path to human genome (masked). Replace it with your path!
human_mask: "/your/folder/HumanGenome/hg19_masked/hg19_masked.fa"
#paths to biobloom filter and accessory text file. Replace it with your paths!
human_bf: "/your/folder/workflow/data/hg19_masked.bf"
human_txt: "/your/folder/workflow/data/hg19_masked.txt"
#path to AR gene bowtie2 database:
AR: "../workflow/data/mr2h_rmnmi"
